# Practice and learn TensorFlow

As we saw in the introduction where we trained a linear regression model using tensorflow, we can algo train a logistic regression following the same steps, just change a litle bit the code.

## Before you start

Of course there is not such a tutorial in the official web page, well almost like these tutorials i really recommend and i learnt a lot:

[GitHub aymericdamien](https://github.com/aymericdamien/TensorFlow-Examples/blob/master/notebooks/2_BasicModels/logistic_regression.ipynb)

[Gentlest Intro to Tensorflow #4: Logistic Regression](https://medium.com/all-of-us-are-belong-to-machines/gentlest-intro-to-tensorflow-4-logistic-regression-2afd0cabc54)

[Lecture note 3: Linear and Logistic Regression in TensorFlow](http://web.stanford.edu/class/cs20si/lectures/notes_03.pdf)

[Using Logistic and Softmax Regression in TensorFlow](https://blog.altoros.com/using-logistic-and-softmax-regression-in-tensorflow.html)

In [1]:
from __future__ import print_function

## Importing

We will use tensorflow to create the graph and train the model and use numpy to handle data

In [2]:
import tensorflow as tf
import numpy as np

## Loading the data

First we load the iris data set that was downloaded from the web page: 

[training](http://download.tensorflow.org/data/iris_training.csv)

[test](http://download.tensorflow.org/data/iris_test.csv)

In [3]:
train = np.loadtxt('iris_training.csv', skiprows=1, delimiter=',')
test = np.loadtxt('iris_test.csv', skiprows=1, delimiter=',')

## Split data

We need to split the data to X and y, remember, the iris dataset has the first four columns and features and the fifth column is the y value.

In [4]:
X_train = train[:, :4]
y_train = train[:, 4]

X_test = test[:, :4]
y_test = test[:, 4]

## Categorical

As we are doing classification, we the to pass the values to one hot encoding
Example: 

[[0], 

 [1],
 
 [2]]
 
to:

[[1, 0, 0],

 [0, 1, 0],
 
 [0, 0, 1]]

In [5]:
y_train = np.eye(3)[y_train.astype('int')]
y_test = np.eye(3)[y_test.astype('int')]

## Features: Features and classes

To train this model we need to declare how many features we have and how many classes

Features:
1. sepal length in cm 
2. sepal width in cm 
3. petal length in cm 
4. petal width in cm 

Classes: 
1. Iris Setosa 
2. Iris Versicolour 
3. Iris Virginica



In [6]:
n_class = y_train.shape[1]
n_feature = X_train.shape[1]

## Number of iterations and learning rate declaration

In [7]:
lr = 0.001
max_iter = 10000

## Placeholders

Remember a placeholder is a variable that we dont specify the value until the model is trained or evaluated

In [8]:
x = tf.placeholder(tf.float32, [None, n_feature])
y = tf.placeholder(tf.float32, [None, n_class])

## Variables

Remember linear regression?

y = W * x + b

Now me have multiples values for x, so we need multiple values for w and b, here we initialize theses values with zeros because for tensorflow is easier to initiliaze values in zeros than other values.

In [9]:
W = tf.Variable(tf.zeros([n_feature, n_class]))
b = tf.Variable(tf.zeros([n_class]))

## Creating the model

The difference here is that we are doing classification, here softmax help us to have values between 0 and 1.

In [10]:
yp = tf.nn.softmax(tf.matmul(x, W) + b)

## The loss function also change

Entropy = y * log(yp)

The probabilty of a event  multiply by the logarithm of this event

In [11]:
loss = tf.reduce_mean(-tf.reduce_sum(y * tf.log(yp), reduction_indices=1))

## The optimizer are always used

In [12]:
optimizer = tf.train.AdamOptimizer(lr)

## Create a variable train 

In [13]:
train = optimizer.minimize(loss)

## Create session and initiliaze all variables

In [14]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

## Training

If we train the model once, we will have a big loss, it is necessary to iterate this process.

In [15]:
for i in range(max_iter):
    sess.run(train, {x: X_train, y: y_train})

## Reassigning W and b

In [16]:
W_value, b_value = sess.run([W, b])

fixW = tf.assign(W, W_value)
fixb = tf.assign(b, b_value)

sess.run([fixW, fixb])

[array([[ 1.15325952,  1.05496025, -1.17063189],
        [ 3.78091812, -0.79020143, -4.81830502],
        [-4.27292204, -0.09086238,  4.60043001],
        [-4.38079691, -4.96103859,  4.62627363]], dtype=float32),
 array([ 4.42134619,  7.47800398, -6.16095543], dtype=float32)]

## Calculating error

In [17]:
loss_value = sess.run(loss, {x: X_test, y: y_test})

loss_value

0.061108276

## It's time to predict and compare

In [18]:
predicted = sess.run(yp, {x: X_test})
np.round(predicted)

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.]], dtype=float32)

In [19]:
predicted = np.argmax(predicted, axis=1)
predicted

array([1, 2, 0, 1, 1, 1, 0, 1, 1, 2, 2, 0, 2, 1, 1, 0, 1, 0, 0, 2, 0, 1, 2,
       1, 1, 1, 0, 1, 2, 1])

In [20]:
y_test = np.argmax(y_test, axis=1)
y_test

array([1, 2, 0, 1, 1, 1, 0, 2, 1, 2, 2, 0, 2, 1, 1, 0, 1, 0, 0, 2, 0, 1, 2,
       1, 1, 1, 0, 1, 2, 1])

## The value we got wrong

In [21]:
predicted - y_test

array([ 0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

## Do not forget to close the session

In [22]:
sess.close()